require('eero.plugins')
require('eero.nvim-tree')
require('eero.telescope')
require('eero.treesitter')
require('eero.lsp')
-- require('eero.toggleterm')
require('feline').setup()
require('nvim-autopairs').setup()
require('Comment').setup()
